# Generated by Django 4.1.6 on 2023-02-02 11:54

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('published_on', models.DateTimeField(db_index=True)),
                ('description', models.TextField()),
                ('small_thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('medium_thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('large_thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('filter', django.db.models.manager.Manager()),
            ],
        ),
    ]
