# Generated by Django 4.1.6 on 2023-02-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='famvideo',
            managers=[
            ],
        ),
    ]
